sudo: required
dist: xenial

language: bash

notifications:
  slack: wordops:MyZBNbI7JfhbAi3YyFckMdaa

addons:
  apt:
    update: true

git:
  quiet: true

before_install:
  - rm -rf ~/.gnupg

before_script:
  - sudo rm -rf /etc/mysql
  - sudo bash -c 'echo example.com > /etc/hostname'
  - sudo apt-get -qq purge mysql* graphviz* redis*
  - sudo apt-get -qq autoremove --purge
  - unset LANG
  - sudo apt-get install --assume-yes --quiet git python3-setuptools python3-dev python3-apt ccze tree

after_script:
  - sudo cat /etc/nginx/nginx.conf | ccze -A
  - sudo cat /etc/mysql/my.cnf | ccze -A
  - sudo bash install --purge
  - sudo curl --progress-bar --upload-file /var/log/wo/wordops.log https://transfer.vtbox.net/"$(basename wordops.log)" && echo "" | sudo tee -a $HOME/.transfer.log && echo ""


script:
  - lsb_release -a
  - sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sed -i 's/# "nose"/"nose"/g' setup.py
  - sed -i 's/# "coverage"/"coverage"/g' setup.py
  - sed -i 's/# "Sphinx >= 1.0"/"Sphinx >= 1.0"/g' setup.py
  - sudo bash install --travis -b "$TRAVIS_BRANCH"
  - sudo bash tests/travis.sh

  - sudo wo update --travis
  - sudo wo stack status
