sudo: required
dist: bionic

language: bash

notifications:
  slack: wordops:MyZBNbI7JfhbAi3YyFckMdaa

addons:
  apt:
    update: true

git:
  quiet: true

cache:
  apt: true

before_install:
  - rm -rf ~/.gnupg

before_script:
  - sudo rm -rf /etc/mysql/
  - sudo bash -c 'echo example.com > /etc/hostname'
  - sudo apt-get -qq purge mysql* graphviz*
  - sudo apt-get -qq autoremove --purge

script:
  - lsb_release -a
  - unset LANG
  - sudo bash -c 'echo -e "[user]\n\tname = abc\n\temail = root@localhost.com" > /home/travis/.gitconfig'
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo apt-get install -qq --force-yes git python3-setuptools python3-dev python3-apt ccze tree
  - sudo bash install --travis
  - sudo wo --help && sudo wo stack install && sudo wo stack install --proftpd
  - sudo wo site create html.net --html && sudo wo site create php.com --php && sudo wo site create mysql.com --mysql && sudo wo site create proxy.com --proxy=127.0.0.1:3000
  - sudo wo site create wp1.com --wp && sudo wo site create wpsc1.net --wpsc && sudo wo site create wpfc1.com --wpfc
  - sudo wo site create wpsc-php73.net --wpsc --php73 && sudo wo site create wpfc-php73.net --wpfc --php73
  - sudo wo site create wpredis.net --wpredis && sudo wo site create wpredis-php73.net --wpredis --php73
  - sudo wo site create wpsubdir1.com --wpsubdir && sudo wo site create wpsubdir-php73.com --wpsubdir --php73

  - sudo wo site create wpsubdirwpsc1.com --wpsubdir --wpsc &&  sudo wo site create wpsubdirwpsc2.com --wpsubdir --wpfc &&  sudo wo site create wpsubdirwpsc1-php73.com --wpsubdir --wpsc --php73 && sudo wo site create wpsubdirwpsc2-php73.com --wpsubdir --wpfc --php73
  - sudo wo site create wpsubdomain1.com --wpsubdomain && sudo wo site create wpsubdomain1-php73.com --wpsubdomain --php73 && sudo wo site create wpsubdomainwpsc.org --wpsubdomain --wpsc && sudo wo site create wpsubdomainwpfc.org --wpsubdomain --wpfc && sudo wo site create wpsubdomainwpfc2.in --wpfc --wpsubdomain

  - sudo wo site create 1.com --html && sudo wo site create 2.com --php && sudo wo site create 3.com --mysql
  - sudo wo site update 1.com --wp && sudo wo site update 2.com --php73 && sudo wo site update 3.com --php73 && sudo wo site update 1.com --wpfc && sudo wo site update 1.com --wpsc && sudo wo site update 1.com --wpredis
  - sudo wp --allow-root --info
  - sudo wo info
  - sudo cat /etc/nginx/nginx.conf
  - sudo cat /etc/mysql/my.cnf
  - sudo wo stack upgrade --netdata --no-prompt
  - sudo wo stack upgrade --phpmyadmin --no-prompt
  - sudo wo stack upgrade --composer --no-prompt
  - sudo wo update --travis
  - sudo wo stack status
  - echo "yes" | sudo wo stack purge --all
  - sudo bash install --purge
