name: test-wordops
version: git
summary: WordOps
description: |
  WordOps is an essential toolset that eases WordPress
  site and server administration. It provide the ability
  to install a high performance WordPress stack
  with a few keystrokes.
confinement: devmode
base: core18

parts:
  test-wordops:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - cement
      - python-apt

apps:
  test-wordops:
    command: wo
